version: '3.4'

services:
    beazybattles.server:
        image: ${DOCKER_REGISTRY-}beazybattlesserver
        build:
            context: .
            dockerfile: BeazyBattles/Server/Dockerfile
        networks:
            test:
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Super_Duper_Password"
            ACCEPT_EULA: "Y"
        networks:
            test:
networks:
    test:
        driver: bridge
